apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-prod
  template:
    metadata:
      labels:
        app: nginx-prod
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: { duration: 20s }
        - setWeight: 100
